export const INVALID_SCHEMA_STATUS_CODE = 400;
export const ALREADY_EXISTS_STATUS_CODE = 403;
export const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
export const RESOURCE_CREATION_SUCCESS_STATUS_CODE = 201;
export const RESOURCE_DOES_NOT_EXIST_STATUS_CODE = 404;
export const SUCCESS_STATUS_CODE = 200;
export const INVALID_AUTH_CREDENTIALS_STATUS_CODE = 401;
